# Generated by Django 6.0.6 on 2026-06-09 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(blank=True, max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('count', 'Count (pieces)'), ('gram_250', '250g'), ('gram_500', '500g'), ('kg_1', '1kg'), ('kg_2', '2kg'), ('litre_1', '1 Litre'), ('custom', 'Custom')], max_length=20)),
                ('custom_unit', models.CharField(blank=True, max_length=50)),
                ('quantity_per_unit', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shops.sellerproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerproduct',
            unique_together={('shop', 'base_product')},
        ),
    ]
